### PR TITLE
sphinx-copybutton added

### PR DESCRIPTION
**Pull request by BryceStansfield**
It seems to work right out of the box. I don't know if it'll require any configuration on ReadTheDoc's end though.

### CODE REVIEW

**Comment by BryceStansfield** [comment]
I think most of these builds should be unneccessary, do you have a PR label that disables them @dhermes ?

**Review by dhermes — APPROVED** [review]
LGTM

**Comment by dhermes** [comment]
@BryceStansfield no changes needed on RTD, it uses `docs/requirements.txt`

> I think most of these builds should be unneccessary

Yes there is a bunch of optimization that could be done here I am just strapped for time

**Comment by dhermes** [comment]
@BryceStansfield Very live now!

Screen Shot 2022-08-28 at 9 52 36 AM

**Comment by BryceStansfield** [comment]
Oh wow, good to see!

**Pull request merged**
